version: "3"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: worldcup 
    ports:
    - "5432:5432"
    networks:
    - world_cup_network 
    volumes:
    - pg-data:/var/lib/postgresql/data
networks:
  world_cup_network:
    driver: bridge
volumes:
  pg-data: